version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: psqlpass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /usr/local/data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
  mem:
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: 1
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
      REDIS_PASSWORD: ""
    ports:
      - '6379:6379'
    volumes:
      - '/usr/local/data/redis:/bitnami/redis/data'
