version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: psqlpass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - /usr/local/data/postgres:/var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432