POST {{api_base_url}}/dist-objects/list
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{}

###
POST {{api_base_url}}/dist-objects/create
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "items": [
    {
      "distribution_id": 1,
      "recipient_id": 2,
      "respondent_id": 7
    }
  ]
}

###
PUT {{api_base_url}}/dist-objects/update
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "item": {
    "id": 1,
    "recipient_id": 2,
    "respondent_id": 7,
    "link_id": 3,
    "publishing_status": "failed"
  }
}

###
DELETE {{api_base_url}}/dist-objects/delete
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "ids": [3]
}