POST {{api_base_url}}/dist-objects/list
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{}

###
POST {{api_base_url}}/dist-objects/create
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "disable_link_creation": false,
  "items": [
    {
      "distribution_id": 1,
      "recipient_id": 24,
      "respondent_id": 82
    }
  ]
}

###
PUT {{api_base_url}}/dist-objects/update
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "item": {
    "id": 1,
    "recipient_id": 2,
    "respondent_id": 7,
    "link_id": 3,
    "publishing_status": "failed"
  }
}

###
DELETE {{api_base_url}}/dist-objects/delete
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "ids": [1]
}