POST {{api_base_url}}/links/list
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

###
POST {{api_base_url}}/links/create
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "disable_auto_generate_hash": false,
  "items": [
    {
      "pin": "122424",
      "usage_limit": 5,
      "attributes": {
        "test": 1
      }
    }
  ]
}

###
PUT {{api_base_url}}/links/update
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "regenerate_hash": true,
  "item": {
    "id": 2,
    "pin": "133535"
  }
}

###
DELETE {{api_base_url}}/links/delete
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "ids": [1,2,3]
}