###
POST {{api_base_url}}/summary/reviews/export
Content-Type: {{content_type}}
Referer: {{referer}}
X-Client-Id: {{client_id}}
X-Authorization: {{auth_token}}

{
  "distribution_id": 1,
  "exclude_status": ["not-started"],
  "file_type": "xlsx"
}

###
POST {{api_base_url}}/summary/distributions
Content-Type: {{content_type}}
Referer: {{referer}}
X-Client-Id: {{client_id}}
X-Authorization: {{auth_token}}

{
  "page": 1,
  "limit": 10
}

###
POST {{api_base_url}}/summary/reviews/data
Content-Type: {{content_type}}
Referer: {{referer}}
X-Client-Id: {{client_id}}
X-Authorization: {{auth_token}}

{
  "distribution_id": 1,
  "recipient_ids": [9,14,15]
}
