POST {{api_base_url}}/login
Content-Type: application/json
Referer: https://anonymity.evorts.com
X-Client-Id: web

{
  "username": "root",
  "password": "ttest11"
}

> {% client.global.set("auth_token", response.body.content.token); %}

### list
POST {{api_base_url}}/users/list
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{}

### create
POST {{api_base_url}}/users/create
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "csrf": "",
  "users": [
    {
      "username": "steven2",
      "display_name": "Steven",
      "attributes": {
        "nik": "1243453"
      },
      "email": "steven2@playground.com",
      "phone": "",
      "password": "testing123",
      "pin": "",
      "access_role": "admin-group",
      "job_role": "engineer",
      "assignment": "bin",
      "group_id": 2,
      "disabled": false
    }
  ]
}

### update
PUT {{api_base_url}}/users/update
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "csrf": "",
  "user": {
    "id": 3,
    "username": "steven3",
    "display_name": "Steven3",
    "attributes": {
      "nik": "1243453"
    },
    "email": "steven@playground2.com",
    "phone": "",
    "password": "testing123",
    "pin": "",
    "access_role": "admin-group",
    "job_role": "engineer",
    "assignment": "bin",
    "group_id": 2,
    "disabled": false
  }
}

### delete
DELETE {{api_base_url}}/users/delete
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "ids": [3]
}