POST {{api_base_url}}/reviews/list
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{}

###
GET {{api_base_url}}/reviews/detail/7
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

###
POST {{api_base_url}}/reviews/submit
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "item": {
    "id": 1,
    "recipient_id": 2,
    "respondent_id": 7,
    "link_id": 3,
    "publishing_status": "failed"
  }
}

