GET {{api_base_url}}/links/list
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

###
POST {{api_base_url}}/links/create
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "csrf": "",
  "disable_auto_generate_hash": false,
  "links": [
    {
      "group_id": 1
    }
  ]
}

###
PUT {{api_base_url}}/links/update
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "csrf": "",
  "regenerate_hash": true,
  "link": {
    "id": 2,
    "group_id": 1,
    "pin": "133535"
  }
}

###
DELETE {{api_base_url}}/links/remove
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "csrf": "",
  "link_id": 2
}