POST {{api_base_url}}/organizations/list
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{}

###
POST {{api_base_url}}/organizations/create
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "orgs": [
    {
      "name": "Testing Organiization2",
      "address": "somewheref"
    }
  ]
}

###
PUT {{api_base_url}}/organizations/update
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "org": {
    "id": 3,
    "name": "Testing Org 2 Update",
    "address": "testnig update addr"
  }
}

###
DELETE {{api_base_url}}/organizations/delete
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "ids": [3]
}