POST {{api_base_url}}/users/forgot-password
Content-Type: {{content_type}}
Referer: {{referer}}
X-Client-Id: {{client_id}}

{
  "username": "rianita.manik@gmail.com",
  "hash": "ldnflksdnfklsnsfgsdlkgniaifd"
}

###
POST {{api_base_url}}/users/create-password
Content-Type: {{content_type}}
Referer: {{referer}}
X-Client-Id: {{client_id}}
X-Authorization: Token adnsdfknslgksdngooiniosdvnsldkgnsdg

{
  "pass": "test@22",
  "confirm": "test@33",
  "hash": "ldnflksdnfklsngsdlkgnd"
}

###
POST {{api_base_url}}/users/login
Content-Type: {{content_type}}
Referer: {{referer}}
X-Client-Id: {{client_id}}

{
  "username": "dev@evorts.com",
  "password": "feeDNom!ty@$$70"
}

> {% client.global.set("auth_token", response.body.content.token); %}

###
POST {{api_base_url}}/users/change-password
Content-Type: {{content_type}}
Referer: {{referer}}
X-Client-Id: {{client_id}}
X-Authorization: {{auth_token}}

{
  "old_pass": "test@11",
  "new_pass": "test@22",
  "confirm": "test@22"
}

### list
POST {{api_base_url}}/users/list
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{}

### create
POST {{api_base_url}}/users/create
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "users": [
    {
      "username": "nando",
      "display_name": "Nando",
      "attributes": {
        "nik": "242532"
      },
      "email": "nando@playground.com",
      "phone": "",
      "password": "nando111",
      "pin": "",
      "access_role": "admin-group",
      "job_role": "engineer",
      "assignment": "bin",
      "group_id": 2,
      "disabled": false
    }
  ]
}

### update
PUT {{api_base_url}}/users/update
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "user": {
    "id": 9,
    "username": "ronald",
    "display_name": "Ronald",
    "attributes": {
      "nik": "232424"
    },
    "email": "ronald@playground.com",
    "phone": "",
    "password": "ronald111",
    "pin": "",
    "access_role": "admin-group",
    "job_role": "Backend Engineer",
    "assignment": "Business Incubation",
    "group_id": 2,
    "disabled": false
  }
}

### delete
DELETE {{api_base_url}}/users/delete
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "ids": [3]
}