POST {{api_base_url}}/distributions/publish
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "force_redistribution": true,
  "ids": [],
  "object_ids": [261,262,263,264,265,266,267,268,269,270],
  "isolate_respondents": [],
  "isolate_recipients": []
}

###
POST {{api_base_url}}/distributions/list
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{}

###
POST {{api_base_url}}/distributions/create
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "items": [
    {
      "topic": "360 Review May 2021",
      "distribution_limit": 5,
      "range_start": "2021-01-01T00:00:00+07:00",
      "range_end": "2021-06-30T23:59:59+07:00",
      "for_group_id": 2
    }
  ]
}

###
PUT {{api_base_url}}/distributions/update
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "item": {
    "id": 1,
    "topic": "360 Review - Business Incubation (Des 2020 ~ May 2021)",
    "for_group_id": 2
  }
}

###
DELETE {{api_base_url}}/distributions/delete
X-Authorization: {{auth_token}}
Content-Type: {{content_type}}
Referer: {{referer}}

{
  "ids": [3]
}