POST {{api_base_url}}/users/login
Content-Type: application/json
Referer: https://anonymity.evorts.com
X-Client-Id: web

{
  "username": "root",
  "password": "ttest11"
}

> {% client.global.set("auth_token", response.body.content.token); %}

### list
POST {{api_base_url}}/users/list
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{}

### create
POST {{api_base_url}}/users/create
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "users": [
    {
      "username": "nando",
      "display_name": "Nando",
      "attributes": {
        "nik": "242532"
      },
      "email": "nando@playground.com",
      "phone": "",
      "password": "nando111",
      "pin": "",
      "access_role": "admin-group",
      "job_role": "engineer",
      "assignment": "bin",
      "group_id": 2,
      "disabled": false
    }
  ]
}

### update
PUT {{api_base_url}}/users/update
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "user": {
    "id": 9,
    "username": "ronald",
    "display_name": "Ronald",
    "attributes": {
      "nik": "232424"
    },
    "email": "ronald@playground.com",
    "phone": "",
    "password": "ronald111",
    "pin": "",
    "access_role": "admin-group",
    "job_role": "Backend Engineer",
    "assignment": "Business Incubation",
    "group_id": 2,
    "disabled": false
  }
}

### delete
DELETE {{api_base_url}}/users/delete
X-Authorization: {{auth_token}}
Content-Type: application/json
Referer: https://anonymity.evorts.com

{
  "ids": [3]
}