/** insert recipients data **/
-- noinspection SqlWithoutWhere
delete from objects;
insert into objects(id, name, email, role, assignment, user_group_id, created_at)
values
       (1,'Abraham Tobing', 'abetobing@protonmail.com', 'Backend Engineer', 'HiRA, Float', 2, now()),
       (2,'Ade Hidayat', 'adeh3101@gmail.com', 'Web Engineer', 'RuangMom', 2, now()),
       (3,'Adryan Fernando Manurung', 'adryanfernandom@gmail.com', 'Web Engineer', 'Prospeku', 2, now()),
       (4,'Ahmad Nursoiman', 'achmadnursoiman@gmail.com', 'HealthTech Consolidator', 'WorkFit, RuangMom', 2, now()),
       (5,'Alan Darmasaputra', 'alanputra0@gmail.com', 'QA Analyst', 'PintuKelas', 2, now()),
       (6,'Aldo Lazuardi', 'aldo.onelabs@gmail.com', 'iOS Engineer', 'PintuKelas', 2, now()),
       (7,'Amirul Faizin', 'altair.muhammad@gmail.com', 'iOS Engineer', 'RuangMom', 2, now()),
       (8,'Anggara Suci Nugraha', 'anggarasucinugraha@gmail.com', 'Android Engineer', 'Koala Living', 2, now()),
       (9,'Balqista Konde', 'balqistakonde@gmail.com', 'QA Analyst', 'Kiddo', 2, now()),
       (10,'Bistok Diiel Lelono', 'bistok@gmail.com', 'PropTech Consolidator', 'Prospeku, Koala Living, Koala Pro', 2, now()),
       (11,'Calista Bertha', 'calistabertha@gmail.com', 'iOS Engineer', 'Koala Living + Team Enabler', 2, now()),
       (12,'Dede Mayangsari', 'dedemayang2706@gmail.com', 'QA Analyst', 'Koala Pro', 2, now()),
       (13,'Diana Gusti Aurora', 'dia.daulay@gmail.com', 'QA Analyst', 'PintuKelas', 2, now()),
       (14,'Didi Dwi Novianto', 'dididwinovianto@gmail.com', 'Infrastructure and Security', 'Onelabs', 2, now()),
       (15,'Echo Simanjuntak', 'echo.w.m.simanjuntak@gmail.com', 'Web Engineer', 'PintuKelas', 2, now()),
       (16,'Edwin Andrianto', 'edwinuad@gmail.com', 'Backend Engineer', 'Koala Pro', 2, now()),
       (17,'Ervina Kwan', 'kwanervina@gmail.com', 'QA Analyst', 'RuangMom', 2, now()),
       (18,'Haris Saputra', 'harissptra@gmail.com', 'Android Engineer', 'PintuKelas', 2, now()),
       (19,'Ian Sembiring', 'ianrajs@gmail.com', 'Web Engineer', 'WorkFit', 2, now()),
       (20,'Melinda Nur Abianti', 'melindanurabianti@gmail.com', '', '', 2, now()),
       (21,'Muhammad Ghozy Ul Haq', 'ghozy.ulhaq@gmail.com', '', '', 2, now()),
       (22,'Muhammad Faizi', 'Muhamadfaizi246@gmail.com', 'Web Engineer', 'Kiddo', 2, now()),
       (23,'Muhammad Rifqi Hanbali', 'mrifqihanbali@gmail.com', '', '', 2, now()),
       (24,'Nicko Prasetyo', 'nickojyj@gmail.com', 'iOS Engineer + Release Manager', 'RuangMom', 2, now()),
       (25,'Nikolaus Ferdy Tanujaya', 'nikz.ferdy@gmail.com', 'Backend Engineer', 'RuangMom', 2, now()),
       (26,'Novita', 'whats.up037@gmail.com', 'Web Engineer', 'Koala Living', 2, now()),
       (27,'Nur Hidayat', 'hidayat.speed78@gmail.com', 'Android Engineer', 'Koala Pro, Prospeku', 2, now()),
       (28,'Oktavianus Sandika', 'okta.sandika@gmail.com', 'QA Analyst', 'HiRA', 2, now()),
       (29,'Ozi Hadithya', 'ozindv@gmail.com', 'QA Analyst + Co-Chapter QA', 'Koala Living', 2, now()),
       (30,'Putri Mulia', 'putrimulia1602@gmail.com', 'QA Analyst', 'RuangMom', 2, now()),
       (31,'Rianita Manik', 'rianita.manik@gmail.com', 'QA Analyst', 'WorkFit', 2, now()),
       (32,'Ruminta Astri Manurung', 'ruminta.astri@gmail.com', 'QA Analyst', 'Prospeku', 2, now()),
       (33,'Safandhi Yonathan', 'safandhi.yonathan@gmail.com', 'Web Engineer', 'RuangMom', 2, now()),
       (34,'Samuel Laluyan', 'sam7ryan@gmail.com', 'Backend Engineer', 'Koala Living', 2, now()),
       (35,'Silvia Tjahjadi', 'silvi.fang@gmail.com', 'Backend Engineer', 'HiRA, Float', 2, now()),
       (36,'Steven Pangemanan', 'work@evorts.com', '', 'Onelabs', 2, now()),
       (37,'Steven Tiolie', 'steventio2011@gmail.com', 'iOS Engineer', 'WorkFit', 2, now()),
       (38,'Wibi Aristama', 'wibi.aristama@gmail.com', 'EduTech Consolidator', 'PintuKelas, Kiddo', 2, now()),
       (39,'Yuni Evalin', 'evalinyuni@gmail.com', 'Android Engineer', 'RuangMom', 2, now())
;